---

subspace_node_install_enabled: true
subspace_node_filesystem_enabled: true
subspace_node_filesystem_list:
  - lv: lv_chimera
    vg: "{{ custom_vg_name }}"
    size: 10g
    path: "{{ subspace_install_path }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false
  - disk: sdc
    path: "{{ subspace_node_install_path }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"
    direct_mount: true

  - lv: lv_subspace_node_log
    vg: "{{ custom_vg_name }}"
    size: 2g
    path: "{{ subspace_node_log_folder }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"
    mode: "0750"
    fstype: xfs
    force: false
    shrink: false

subspace_operator_filesystem_enabled: false
subspace_operator_install_enabled: false

subspace_farmer_install_enabled: true
subspace_farmer_disks:
  - path={{ subspace_farmer_install_path }}/alpha,size=3.5T
subspace_farmer_filesystem_enable: true
subspace_farmer_filesystem_list:
  - lv: lv_subspace_farmer_log
    vg: "{{ custom_vg_name }}"
    size: 2g
    path: "{{ subspace_farmer_log_folder }}"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"
  - disk: sdb
    path: "{{ subspace_farmer_install_path }}/alpha"
    owner: "{{ subspace_owner }}"
    group: "{{ subspace_group }}"
    direct_mount: true

subspace_farmer_port: 50533
subspace_node_p2p_port: 50333
subspace_node_dsn_port: 50433
